version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install pciutils
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            source venv/bin/activate
            python3 -m unittest discover tests
      - store_artifacts:
          path: test-reports
          destination: test-reports

